apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{ .Values.name  }}-ss
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  serviceName: {{ .Values.name }}-service
  selector:
    matchLabels:
      app: {{ .Values.name }}
  volumeClaimTemplates:
    - metadata:
       name: {{ .Values.name }}-vol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: {{ .Values.deployment.repo }}:{{ .Values.deployment.tag }}
          volumeMounts:
            - name: {{ .Values.name }}-vol
              mountPath: {{ .Values.deployment.mountPath }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env: 
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{ end }} 

